FROM python:3.13-slim
RUN apt-get update && apt-get install -y git

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

CMD ["sh", "-c", "flask db upgrade && gunicorn main:app --bind 0.0.0.0:$PORT"]