"""Añadir user_question a la tabla ConversationEval

Revision ID: 12b5fe41264c
Revises: 22ed5f6808e2
Create Date: 2025-09-28 16:18:33.270798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12b5fe41264c'
down_revision = '22ed5f6808e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversation_evals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_question', sa.Text(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversation_evals', schema=None) as batch_op:
        batch_op.drop_column('user_question')

    # ### end Alembic commands ###
