"""Eliminar context_precision y context_recall de ConversationEval

Revision ID: 22ed5f6808e2
Revises: 5fd6f93cca11
Create Date: 2025-09-28 15:22:17.018632

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22ed5f6808e2'
down_revision = '5fd6f93cca11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversation_evals', schema=None) as batch_op:
        batch_op.drop_column('context_precision')
        batch_op.drop_column('context_recall')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversation_evals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('context_recall', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('context_precision', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
