"""Añadir tabla GoldenDataset para evaluación offline

Revision ID: 8aa3f43c06d4
Revises: c379d75da6fd
Create Date: 2025-09-28 14:07:16.685626

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8aa3f43c06d4'
down_revision = 'c379d75da6fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('golden_dataset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('ground_truth', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('question')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('golden_dataset')
    # ### end Alembic commands ###
