"""Añadir generated_answer a EvaluationResult

Revision ID: b444fa28aa71
Revises: 12b5fe41264c
Create Date: 2025-09-28 17:40:46.398508

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b444fa28aa71'
down_revision = '12b5fe41264c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evaluation_results', schema=None) as batch_op:
        batch_op.add_column(sa.Column('generated_answer', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evaluation_results', schema=None) as batch_op:
        batch_op.drop_column('generated_answer')

    # ### end Alembic commands ###
