"""Añadir tabla ConversationEval para métricas Ragas

Revision ID: c379d75da6fd
Revises: 694f527c1374
Create Date: 2025-09-28 12:07:57.055590

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c379d75da6fd'
down_revision = '694f527c1374'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation_evals',
    sa.Column('eval_id', sa.String(), nullable=False),
    sa.Column('message_id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('faithfulness', sa.Float(), nullable=True),
    sa.Column('answer_relevancy', sa.Float(), nullable=True),
    sa.Column('context_precision', sa.Float(), nullable=True),
    sa.Column('context_recall', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['chat_messages.message_id'], ),
    sa.PrimaryKeyConstraint('eval_id'),
    sa.UniqueConstraint('message_id')
    )
    with op.batch_alter_table('conversation_evals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conversation_evals_session_id'), ['session_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversation_evals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conversation_evals_session_id'))

    op.drop_table('conversation_evals')
    # ### end Alembic commands ###
